# Generated by Django 3.0.4 on 2020-03-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='track',
            new_name='post',
        ),
    ]
