# Generated by Django 3.0.4 on 2020-03-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0011_auto_20200318_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posted_by',
            new_name='user',
        ),
    ]
