# Generated by Django 3.0.4 on 2020-03-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0012_auto_20200318_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
